[package]
name = "local-outlier-probabilities"
version = "1.2.0"
edition = "2021"
description = "Local Outlier Probabilities (LoOP) calculation"
repository = "https://github.com/medbioinf/loop-rs"
homepage = "https://github.com/medbioinf/loop-rs"
documentation = "https://docs.rs/local-outlier-probabilities"
license-file = "LICENSE"
readme = "Readme.md"

[dependencies]
kdtree = "0.7.0"
num-traits = "0.2.19"
rayon = { version = "1", optional = true }
thiserror = "2.0.12"

[features]
default = []
parallel = ["dep:rayon"]

[dev-dependencies]
ndarray = "0.16.1"
ndarray-stats = "0.6.0"
polars = { version = "0.47.1", features = ["ndarray"] }
